# Generated by Django 3.0 on 2021-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Usuario habilitado/Usuario deshabilitado'),
        ),
    ]
