# Generated by Django 3.0 on 2021-03-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='fix-me', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='insta',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nacionalidad',
            field=models.CharField(default='fix-me', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupacion',
            field=models.CharField(default='fix-me', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='snapchat',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='wapp',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='web',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.CharField(default='fix-me', max_length=100),
            preserve_default=False,
        ),
    ]
