# Generated by Django 3.0 on 2021-03-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_estado'),
        ('users', '0002_auto_20210307_1908'),
    ]

    operations = [
    ]
