# Generated by Django 3.0 on 2021-02-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
