# Generated by Django 3.0 on 2021-03-08 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 20, 8, 54, 832761, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
