# Generated by Django 3.0 on 2021-03-08 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210308_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 20, 9, 0, 360894, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
