# Generated by Django 3.0 on 2021-03-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210316_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(default='elegir categoria', max_length=255),
        ),
    ]
