# Generated by Django 3.0 on 2021-03-19 16:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210317_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
